# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "lazy-head-gen"
  s.version = "0.6.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Stuart Chinery", "Dave Hrycyszyn"]
  s.date = "2012-10-05"
  s.description = "lazy-head-gen adds some extra generators to Padrino. Currently they are hard wired to use ActiveRecord and MiniTest."
  s.email = "stuart.chinery@headlondon.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lazy-head-gen.gemspec",
    "lib/lazy-head-gen.rb",
    "lib/lazy-head-gen/admin_controller_test.rb",
    "lib/lazy-head-gen/scaffold.rb",
    "lib/lazy-head-gen/templates/admin_controller_test/admin_controller_test.rb.tt",
    "lib/lazy-head-gen/templates/scaffold/blueprints.rb.tt",
    "lib/lazy-head-gen/templates/scaffold/controller.rb.tt",
    "lib/lazy-head-gen/templates/scaffold/controller_test.rb.tt",
    "lib/lazy-head-gen/templates/scaffold/helper.rb.tt",
    "lib/lazy-head-gen/templates/scaffold/model.rb.tt",
    "lib/lazy-head-gen/templates/scaffold/model_test.rb.tt",
    "lib/lazy-head-gen/templates/scaffold/view.erb.tt",
    "test/helper.rb",
    "test/lazy-head-gen/test_admin_controller_test.rb",
    "test/lazy-head-gen/test_scaffold.rb",
    "test/test_lazy-head-gen.rb"
  ]
  s.homepage = "http://github.com/sleepingstu/lazy-head-gen"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.19"
  s.summary = "Some extra generators for Padrino, using ActiveRecord and MiniTest."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<padrino>, [">= 0"])
      s.add_development_dependency(%q<minitest>, [">= 0"])
      s.add_development_dependency(%q<turn>, ["~> 0.9.5"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_development_dependency(%q<uuid>, [">= 0"])
    else
      s.add_dependency(%q<padrino>, [">= 0"])
      s.add_dependency(%q<minitest>, [">= 0"])
      s.add_dependency(%q<turn>, ["~> 0.9.5"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_dependency(%q<uuid>, [">= 0"])
    end
  else
    s.add_dependency(%q<padrino>, [">= 0"])
    s.add_dependency(%q<minitest>, [">= 0"])
    s.add_dependency(%q<turn>, ["~> 0.9.5"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<yard>, ["~> 0.6.0"])
    s.add_dependency(%q<uuid>, [">= 0"])
  end
end

